import { IDropdownOption } from "@fluentui/react"

export const states: IDropdownOption[] = [
  { key: "AK", text: "Alaska" },
  { key: "AL", text: "Alabama" },
  { key: "AR", text: "Arkansas" },
  { key: "AS", text: "American Samoa" },
  { key: "AZ", text: "Arizona" },
  { key: "CA", text: "California" },
  { key: "CO", text: "Colorado" },
  { key: "CT", text: "Connecticut" },
  { key: "DC", text: "District Of Columbia" },
  { key: "DE", text: "Delaware" },
  { key: "FL", text: "Florida" },
  { key: "GA", text: "Georgia" },
  { key: "GU", text: "Guam" },
  { key: "HI", text: "Hawaii" },
  { key: "IA", text: "Iowa" },
  { key: "ID", text: "Idaho" },
  { key: "IL", text: "Illinois" },
  { key: "IN", text: "Indiana" },
  { key: "KS", text: "Kansas" },
  { key: "KY", text: "Kentucky" },
  { key: "LA", text: "Louisiana" },
  { key: "MA", text: "Massachusetts" },
  { key: "MD", text: "Maryland" },
  { key: "ME", text: "Maine" },
  { key: "MI", text: "Michigan" },
  { key: "MN", text: "Minnesota" },
  { key: "MO", text: "Missouri" },
  { key: "MP", text: "Northern Mariana Islands" },
  { key: "MS", text: "Mississippi" },
  { key: "MT", text: "Montana" },
  { key: "NC", text: "North Carolina" },
  { key: "ND", text: "North Dakota" },
  { key: "NE", text: "Nebraska" },
  { key: "NH", text: "New Hampshire" },
  { key: "NJ", text: "New Jersey" },
  { key: "NM", text: "New Mexico" },
  { key: "NV", text: "Nevada" },
  { key: "NY", text: "New York" },
  { key: "OH", text: "Ohio" },
  { key: "OK", text: "Oklahoma" },
  { key: "OR", text: "Oregon" },
  { key: "PA", text: "Pennsylvania" },
  { key: "PR", text: "Puerto Rico" },
  { key: "RI", text: "Rhode Island" },
  { key: "SC", text: "South Carolina" },
  { key: "SD", text: "South Dakota" },
  { key: "TN", text: "Tennessee" },
  { key: "TX", text: "Texas" },
  { key: "UM", text: "United States Minor Outlying Islands" },
  { key: "UT", text: "Utah" },
  { key: "VA", text: "Virginia" },
  { key: "VI", text: "Virgin Islands" },
  { key: "VT", text: "Vermont" },
  { key: "WA", text: "Washington" },
  { key: "WI", text: "Wisconsin" },
  { key: "WV", text: "West Virginia" },
  { key: "WY", text: "Wyoming" },
]
