# TODO: Skip the local build by using skip_app_build. Use an artifact instead
# TODO: yarn install --frozen-lockfile --ignore-scripts to skip postinstall
# TODO: use app_build_command to create a custom build script

name: Release Frontend

on:
  push:
    branches:
      - main

jobs:
  staging_deployment:
    environment:
      name: Staging
      url: https://staging.fencing.club
    runs-on: ubuntu-latest
    name: Deploy to Staging
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: deploystaging
        uses: Azure/static-web-apps-deploy@v1
        with:
          production_branch: "main"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_COAST_047525A1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "/dist"

  production_deployment:
    environment:
      name: Production
      url: https://fencing.club
    needs: staging_deployment
    runs-on: ubuntu-latest
    name: Deploy to Production
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Deploy Production
        id: deployproduction
        uses: Azure/static-web-apps-deploy@v1
        with:
          production_branch: "main"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_BEACH_056E5171E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "/dist"
